### ISSUE TITLE
tcc: No such file or directory

### ISSUE THREAD

**Issue by dinhero21** [jcnils/protonhax#12]
It seems there has been a typo in the [Makefile](https://github.com/jcnils/protonhax/blob/c13301687f5c417d2fb4aa5b9fefd48e719a2c9b/Makefile#L11) file.

When I run `make`, there is an attempt to call `tcc` which might be [Tiny C Compiler](https://bellard.org/tcc/) but I find that unlikely since it wasn't declared as a reference.

Changing it to `gcc` makes the program build successfully.

I was going to make a PR but I just want to be sure this is indeed a typo and not intentional.

**Comment by jcnils** [comment]
Hi @Dinhero21 thanks for the report. 

I am sorry I missed that, it was an oversight because I was mostly using arch at the time and the requirement is on their [pkgbuild](https://aur.archlinux.org/packages/protonhax). I will update the reference for tcc, for now. 

I will leave this open because of 2 things:

- it would be best to use whatever people have on their system instead of installing additional software (if they have gcc there is no need to also install tcc, and vice versa).
- https://github.com/jcnils/protonhax/issues/11 suggest doing everything with bash, so we might not even need to compile (but I need to run some tests first).

**Comment by jcnils** [comment]
The last update only relies on bash script, so there is no need of gcc or tcc.
