### ISSUE TITLE
Protonhax in launch options line causes games not to launch

### ISSUE THREAD

**Issue by Krythulu** [jcnils/protonhax#16]
Evening,

I install Protonhax and I attempted to launch GRAND THEFT AUTO V with the launch properties line `protonhax init %COMMAND%`. However whenever I launch the game, it doesn't do anything. It just says "launching" then it stops.

Steps to reproduce
1. Git clone Protonhax
2. Add executable perms
3. Add protonhax to path
4. Change launch perms to protonhax init %COMMAND%

I even attempted to launch Core Keeper with the same command line but it doesn't work. Any tips would be appreciated

OS: Linux Mint 21
Steam Version: Native

Hope this gets patched

**Comment by ruudschouten** [comment]
I had the same issue, most likely because I didn't update the `PATH` correctly with the location for where I put `protonhax`, as I only updated the `PATH` value in my ~/.bashrc.
So, the way I was able to fix it was by launching Steam with a terminal, so it also uses the ~./bashrc file.

So, in your case, Steam could also likely not find the `protonhax` executable file on your `PATH`.

**Comment by jcnils** [comment]
Thanks @ruudschouten, usually that is the best way to solve protonhax not being found in the path

@Krythulu If you are running those games using proton(those games offer Linux native), and if you are not using [steam flatpak](https://github.com/jcnils/protonhax/issues/9), there are a few places too look to troubleshoot this:

- what is going on when you start the game
- verify the game is in the path
- verify if steam can see the path.
- verify what the protonhax script is doing.

### verify the game is in the path

Open terminal and run `protonhax`, if it returns the info, success. 

You can also run `type -a protonhax` to check the path to the file.

### verify if steam can see protonhax path/ what is going on when you start the game

The easiest way is to check if other tools you have in the $PATH are working, like `mangohud %command%`, or gamescope, or any other program. If it can, it means that steam can see some paths, but not others.

Alternatively, you can try to run steam from the terminal, and try to run the game pay attention to any message like `protonhax not found`.

Depending on how you installed steam(e.g. distrobox), there is a chance the game will recognize the path when run from a terminal, but not from the applications' menu.

### pt2 what is going on when you start the game

PROTON_LOG=1 protonhax init %command%

steam will save proton log into your home folder.

**Comment by TheAgamer554** [comment]
I have this exact issue and after testing I've found that steam does in fact not find the protonhax command `/bin/sh: line 1: protonhax: command not found` even though it's in the path and I even tried running steam from the terminal. I'm on Fedora 40 and running steam binary so this isn't a flatpak issue at all

Edit: i was able to bypass it by using the absolute path, but it would be helpful to know how to make it work with the path

**Comment by jcnils** [comment]
@TheAgamer554 Thanks for sharing your solution, please let me know if you figure it out what is happening in your case. 

I saw different cases of Steam not finding the path, usually by not knowing where it is or not having access privileges to it - like when it runs from containers like flatpak or distro box.

I wonder if Steam is looking into specific paths, rather than $PATH.  Can you please try protonhax on '/usr/bin' or '/usr/local/bin'?

**Comment by jcnils** [comment]
I will close this for now, as it seems to be a problem of steam not finding protonhax path and I haven't heard from @Krythulu in a while. - Feel free to open again to provide additional information.

Besides starting steam from the terminal, try passing the full path to protonhax in the launch options `/your/path/to/protonhax init %command%`
